openapi: 3.0.0

info:
  title: API
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Development

tags:
  - name: admin

paths:
  /admin/authentication:
    post:
      tags:
        - admin
      description: "Authentication"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      role:
                        type: string
                      token:
                        type: string
                  errors:
                    type: array
                    items:
                      type: string
